# Generated by Django 4.2.24 on 2025-10-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0002_alter_booking_options_booking_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedbooking',
            name='booked_for',
            field=models.CharField(blank=True, default='Self', max_length=200),
        ),
        migrations.AddField(
            model_name='archivedbooking',
            name='organization',
            field=models.CharField(blank=True, default='Not specified', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_for',
            field=models.CharField(blank=True, default='Self', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='organization',
            field=models.CharField(blank=True, default='Not specified', max_length=200),
        ),
        migrations.AlterField(
            model_name='archivedbooking',
            name='additional_support',
            field=models.TextField(blank=True, default='No additional support needed'),
        ),
    ]
