# Generated by Django 4.2.24 on 2025-10-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0003_archivedbooking_booked_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedbooking',
            name='booked_for',
            field=models.CharField(blank=True, default='Self', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='archivedbooking',
            name='organization',
            field=models.CharField(blank=True, default='Not specified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_for',
            field=models.CharField(blank=True, default='Self', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='organization',
            field=models.CharField(blank=True, default='Not specified', max_length=100, null=True),
        ),
    ]
