# """
# Django settings for BdOSN project.

# Generated by 'django-admin startproject' using Django 5.2.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.2/ref/settings/
# """

# from pathlib import Path
# import os
# from urllib.parse import urlparse
# import dj_database_url
# from django.core.exceptions import ImproperlyConfigured


# def env_flag(name, default=False):
#     return os.environ.get(name, str(default)).lower() in {"1", "true", "yes", "on"}


# def env_list(name):
#     return [value.strip() for value in os.environ.get(name, "").split(",") if value.strip()]


# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent



# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# # `development` is the default for local runs. Set `DJANGO_ENV=production`
# # on any deployment platform, including Vercel.
# DJANGO_ENV = os.environ.get("DJANGO_ENV", "development").lower()
# IS_PRODUCTION = DJANGO_ENV == "production" or env_flag("VERCEL")

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
# if not SECRET_KEY:
#     if IS_PRODUCTION:
#         raise ImproperlyConfigured("DJANGO_SECRET_KEY must be set in production.")
#     SECRET_KEY = "local-development-only-key-change-me"

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = env_flag("DJANGO_DEBUG", default=not IS_PRODUCTION)
# if IS_PRODUCTION and DEBUG:
#     raise ImproperlyConfigured("DJANGO_DEBUG must be False in production.")

# vercel_hosts = []
# for variable in ("VERCEL_URL", "VERCEL_BRANCH_URL", "VERCEL_PROJECT_PRODUCTION_URL"):
#     host = os.environ.get(variable, "").split(":", 1)[0].strip()
#     if host:
#         vercel_hosts.append(host)

# ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS")
# if not ALLOWED_HOSTS and not IS_PRODUCTION:
#     ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]"]
# for host in vercel_hosts:
#     if host not in ALLOWED_HOSTS:
#         ALLOWED_HOSTS.append(host)
# if env_flag("VERCEL") and ".vercel.app" not in ALLOWED_HOSTS:
#     ALLOWED_HOSTS.append(".vercel.app")
# if IS_PRODUCTION and not ALLOWED_HOSTS:
#     raise ImproperlyConfigured("DJANGO_ALLOWED_HOSTS must be set in production.")

# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     "BookingSystem"
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'whitenoise.middleware.WhiteNoiseMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'BdOSN.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': ["templates"],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'BdOSN.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# # database_url = os.environ.get("DATABASE_URL")
# # if database_url:
# #     parsed_database_url = urlparse(database_url)
# #     has_placeholder = (
# #         parsed_database_url.username == "user"
# #         or parsed_database_url.password == "password"
# #         or parsed_database_url.hostname == "host"
# #         or parsed_database_url.path.lstrip("/") == "database"
# #     )
# # else:
# #     has_placeholder = False
# # if has_placeholder:
# #     raise ImproperlyConfigured(
# #         "DATABASE_URL still contains example placeholder values. Set it to the real PostgreSQL URL from your database provider."
# #     )
# # if IS_PRODUCTION and not database_url:
# #     raise ImproperlyConfigured(
# #         "DATABASE_URL must be configured in production; SQLite is not suitable for deployment."
# #     )
# # if database_url:
# #     database_config = dj_database_url.parse(
# #         database_url,
# #         conn_max_age=0 if IS_PRODUCTION else 600,
# #         conn_health_checks=True,
# #         ssl_require=not DEBUG,
# #     )
# #     if IS_PRODUCTION and database_config["ENGINE"] == "django.db.backends.sqlite3":
# #         raise ImproperlyConfigured(
# #             "A PostgreSQL DATABASE_URL is required in production; SQLite is not supported."
# #         )
# #     DATABASES = {
# #         "default": database_config
# #     }
# # else:
# #     DATABASES = {
# #         "default": {
# #             "ENGINE": "django.db.backends.sqlite3",
# #             "NAME": BASE_DIR / "db.sqlite3",
# #         }
# #     }


# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": "railway",
#         "USER": "postgres",
#         "PASSWORD": "RjHZwfvdxRFHUipVFVwCRpeFQnLzdSTj",
#         "HOST": "hopper.proxy.rlwy.net",
#         "PORT": "36346",
#     }
# }





# # Password validation
# # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'Asia/Dhaka'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = '/static/'

# STATIC_ROOT = BASE_DIR / 'staticfiles'
# STATICFILES_DIRS = [
#     BASE_DIR / 'static',
# ]

# STORAGES = {
#     "default": {
#         "BACKEND": "django.core.files.storage.FileSystemStorage",
#     },
#     "staticfiles": {
#         "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
#     },
# }

# # Default primary key field type
# # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# SECURE_SSL_REDIRECT = not DEBUG
# SESSION_COOKIE_SECURE = not DEBUG
# CSRF_COOKIE_SECURE = not DEBUG
# SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
# SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
# SECURE_HSTS_PRELOAD = not DEBUG
# SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# X_FRAME_OPTIONS = "DENY"

# CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS")
# for host in vercel_hosts:
#     origin = f"https://{host}"
#     if origin not in CSRF_TRUSTED_ORIGINS:
#         CSRF_TRUSTED_ORIGINS.append(origin)

# # ========================================



"""
Django settings for BdOSN project.

Generated by 'django-admin startproject' using Django 5.2.
"""

from pathlib import Path
import os

import dj_database_url
from django.core.exceptions import ImproperlyConfigured


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# ENVIRONMENT HELPERS
# ============================================================

def env_flag(name, default=False):
    return os.environ.get(
        name,
        str(default)
    ).lower() in {"1", "true", "yes", "on"}


def env_list(name):
    return [
        value.strip()
        for value in os.environ.get(name, "").split(",")
        if value.strip()
    ]


# ============================================================
# ENVIRONMENT
# ============================================================

DJANGO_ENV = os.environ.get(
    "DJANGO_ENV",
    "development"
).lower()

IS_PRODUCTION = (
    DJANGO_ENV == "production"
    or env_flag("VERCEL")
)


# ============================================================
# SECRET KEY
# ============================================================

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

if not SECRET_KEY:
    if IS_PRODUCTION:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY must be set in production."
        )

    SECRET_KEY = "local-development-only-key-change-me"


# ============================================================
# DEBUG
# ============================================================

DEBUG = env_flag(
    "DJANGO_DEBUG",
    default=not IS_PRODUCTION
)

if IS_PRODUCTION and DEBUG:
    raise ImproperlyConfigured(
        "DJANGO_DEBUG must be False in production."
    )


# ============================================================
# ALLOWED HOSTS
# ============================================================

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS")


# Local development
if not IS_PRODUCTION:
    ALLOWED_HOSTS += [
        "localhost",
        "127.0.0.1",
        "[::1]",
    ]


# Vercel domains
vercel_hosts = []

for variable in (
    "VERCEL_URL",
    "VERCEL_BRANCH_URL",
    "VERCEL_PROJECT_PRODUCTION_URL",
):
    host = os.environ.get(variable, "").strip()

    if host:
        host = host.split(":", 1)[0]
        vercel_hosts.append(host)


for host in vercel_hosts:
    if host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)


# Allow Vercel preview domains
if env_flag("VERCEL"):
    if ".vercel.app" not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(".vercel.app")


# Production safety check
if IS_PRODUCTION and not ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        "DJANGO_ALLOWED_HOSTS must be configured in production."
    )


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "BookingSystem",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # Serve static files through WhiteNoise
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# URL / WSGI
# ============================================================

ROOT_URLCONF = "BdOSN.urls"

WSGI_APPLICATION = "BdOSN.wsgi.application"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [
            BASE_DIR / "templates",
        ],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ============================================================
# DATABASE
# PostgreSQL - Railway
# ============================================================

DATABASE_URL = os.environ.get("DATABASE_URL")

if not DATABASE_URL:
    if IS_PRODUCTION:
        raise ImproperlyConfigured(
            "DATABASE_URL must be configured in production."
        )
else:
    DATABASE_CONFIG = dj_database_url.parse(
        DATABASE_URL,

        # Vercel is serverless.
        # Do not keep persistent DB connections alive.
        conn_max_age=0,

        # Check connections before using them.
        conn_health_checks=True,

        # Railway PostgreSQL should use SSL.
        ssl_require=IS_PRODUCTION,
    )

    # Never allow SQLite in production
    if (
        IS_PRODUCTION
        and DATABASE_CONFIG["ENGINE"]
        != "django.db.backends.postgresql"
    ):
        raise ImproperlyConfigured(
            "Production requires PostgreSQL. "
            "SQLite is not supported."
        )

    DATABASES = {
        "default": DATABASE_CONFIG
    }


# Local development fallback
if not DATABASE_URL and not IS_PRODUCTION:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME":
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator",
    },
    {
        "NAME":
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator",
    },
    {
        "NAME":
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator",
    },
    {
        "NAME":
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator",
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Dhaka"

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# WhiteNoise / Django 5.2 storage configuration
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },

    "staticfiles": {
        "BACKEND":
            "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ============================================================
# SECURITY
# ============================================================

SECURE_PROXY_SSL_HEADER = (
    "HTTP_X_FORWARDED_PROTO",
    "https",
)

SECURE_SSL_REDIRECT = IS_PRODUCTION

SESSION_COOKIE_SECURE = IS_PRODUCTION

CSRF_COOKIE_SECURE = IS_PRODUCTION

SECURE_HSTS_SECONDS = (
    31536000 if IS_PRODUCTION else 0
)

SECURE_HSTS_INCLUDE_SUBDOMAINS = IS_PRODUCTION

SECURE_HSTS_PRELOAD = IS_PRODUCTION

X_FRAME_OPTIONS = "DENY"


# ============================================================
# CSRF TRUSTED ORIGINS
# ============================================================

CSRF_TRUSTED_ORIGINS = env_list(
    "DJANGO_CSRF_TRUSTED_ORIGINS"
)


# Automatically trust Vercel URLs
for host in vercel_hosts:
    origin = f"https://{host}"

    if origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)


# ============================================================
# OPTIONAL: CUSTOM DOMAIN
# ============================================================

CUSTOM_DOMAIN = os.environ.get(
    "CUSTOM_DOMAIN",
    ""
).strip()

if CUSTOM_DOMAIN:
    if CUSTOM_DOMAIN not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(CUSTOM_DOMAIN)

    custom_origin = f"https://{CUSTOM_DOMAIN}"

    if custom_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(custom_origin)